CREATE TABLE [dbo].[IMAGE_TBL] (
  [IMAGEID] [numeric] NOT NULL,
  [USERID] [numeric] NULL,
  [BUCKETID] [numeric] NULL,
  [PROFILEID] [numeric] NULL,
  [IMAGE_NAME] [varchar](100) NULL,
  [IMAGEH] [varchar](max) NULL,
  [IMAGEM] [varchar](max) NULL,
  [IMAGEL] [varchar](max) NULL,
  [IMAGE_THUMB] [image] NULL,
  [HIDE_FLG] [char](1) NULL,
  [created_dt] [date] NULL,
  [created_by] [varchar](50) NULL,
  CONSTRAINT [PK_IMAGE_TBL] PRIMARY KEY CLUSTERED ([IMAGEID])
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[IMAGE_TBL]
  ADD CONSTRAINT [FK_BUCKETID_IMAGE_TBL] FOREIGN KEY ([BUCKETID]) REFERENCES [dbo].[BUCKET_MSTR] ([BUCKETID])
GO

ALTER TABLE [dbo].[IMAGE_TBL]
  ADD CONSTRAINT [FK_PROFILEID_IMAGE_TBL] FOREIGN KEY ([PROFILEID]) REFERENCES [dbo].[PROFILE_MSTR] ([PROFILEID])
GO

ALTER TABLE [dbo].[IMAGE_TBL]
  ADD CONSTRAINT [FK_USER_ID_IMAGE_TBL] FOREIGN KEY ([USERID]) REFERENCES [dbo].[USER_ROLE_MSTR] ([USERID])
GO